version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"

  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf
    ports:
      - "8080:80"
